// AUTO-GENERATED by scripts/sync-catalog.mjs. DO NOT EDIT.
// Run: pnpm sync-catalog
// Source: PlatformBackend/cost/api/_chat_models.json

export type GeneratedCatalogEntry = {
  id: string;
  name: string;
  reasoning: boolean;
  vision: boolean;
  contextWindow: number;
  maxTokens: number;
  cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
};

export const GENERATED_CHAT_MODELS: readonly GeneratedCatalogEntry[] = [
  { id: "gpt-4.1-mini", name: "GPT-4.1 mini", reasoning: false, vision: false, contextWindow: 128000, maxTokens: 8192, cost: {"input":0.147173075,"output":0.58869265,"cacheRead":0.036793225,"cacheWrite":0} },
] as const;
