// AUTO-GENERATED by scripts/sync-catalog.mjs. DO NOT EDIT.
// Run: pnpm sync-catalog
// Source: PlatformBackend/cost/api/_chat_models.json

export type GeneratedCatalogEntry = {
  id: string;
  name: string;
  reasoning: boolean;
  vision: boolean;
  contextWindow: number;
  maxTokens: number;
};

export const GENERATED_CHAT_MODELS: readonly GeneratedCatalogEntry[] = [
  { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", reasoning: true, vision: true, contextWindow: 1000000, maxTokens: 128000 },
  { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5", reasoning: true, vision: true, contextWindow: 1000000, maxTokens: 64000 },
  { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 64000 },
  { id: "claude-opus-4-8", name: "Claude Opus 4.8", reasoning: true, vision: true, contextWindow: 1000000, maxTokens: 128000 },
  { id: "claude-opus-4-7", name: "Claude Opus 4.7", reasoning: true, vision: true, contextWindow: 1000000, maxTokens: 128000 },
  { id: "claude-opus-4-6", name: "Claude Opus 4.6", reasoning: true, vision: true, contextWindow: 1000000, maxTokens: 128000 },
  { id: "claude-opus-4-5-20251101", name: "Claude Opus 4.5", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 64000 },
  { id: "claude-opus-4-20250514", name: "Claude Opus 4", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 32000 },
  { id: "claude-opus-4-1-20250805", name: "Claude Opus 4.1", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 32000 },
  { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5", reasoning: false, vision: true, contextWindow: 200000, maxTokens: 8192 },
  { id: "claude-3-opus-20240229", name: "Claude 3 Opus", reasoning: false, vision: true, contextWindow: 200000, maxTokens: 4096 },
  { id: "claude-3-7-sonnet-20250219", name: "Claude 3.7 Sonnet", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 64000 },
  { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet", reasoning: false, vision: true, contextWindow: 200000, maxTokens: 8192 },
  { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku", reasoning: false, vision: true, contextWindow: 200000, maxTokens: 8192 },
  { id: "gpt-5.4-nano", name: "GPT-5.4 nano", reasoning: true, vision: true, contextWindow: 400000, maxTokens: 16384 },
  { id: "gpt-5.4-mini", name: "GPT-5.4 mini", reasoning: true, vision: true, contextWindow: 400000, maxTokens: 16384 },
  { id: "gpt-5.2-pro", name: "GPT-5.2 Pro", reasoning: true, vision: true, contextWindow: 400000, maxTokens: 32768 },
  { id: "gpt-5.1-all", name: "GPT-5.1 all", reasoning: true, vision: true, contextWindow: 400000, maxTokens: 16384 },
  { id: "gpt-5-all", name: "GPT-5 all", reasoning: true, vision: true, contextWindow: 400000, maxTokens: 16384 },
  { id: "gpt-4o-mini", name: "GPT-4o mini", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 16384 },
  { id: "gpt-4o-image", name: "GPT-4o image", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 16384 },
  { id: "gpt-4o-all", name: "GPT-4o all", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 16384 },
  { id: "gpt-4o", name: "GPT-4o", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 16384 },
  { id: "gpt-4.1-nano", name: "GPT-4.1 nano", reasoning: false, vision: true, contextWindow: 1000000, maxTokens: 32768 },
  { id: "gpt-4.1-mini", name: "GPT-4.1 mini", reasoning: false, vision: true, contextWindow: 1000000, maxTokens: 32768 },
  { id: "gpt-4.1", name: "GPT-4.1", reasoning: false, vision: true, contextWindow: 1000000, maxTokens: 32768 },
  { id: "o4-mini", name: "o4 mini", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 100000 },
  { id: "o3-pro", name: "o3 pro", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 100000 },
  { id: "o3-mini", name: "o3 mini", reasoning: true, vision: false, contextWindow: 200000, maxTokens: 100000 },
  { id: "o3", name: "o3", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 100000 },
  { id: "o1-pro", name: "o1 pro", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 100000 },
  { id: "o1-mini", name: "o1 mini", reasoning: true, vision: false, contextWindow: 128000, maxTokens: 65536 },
  { id: "o1", name: "o1", reasoning: true, vision: true, contextWindow: 200000, maxTokens: 100000 },
  { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", reasoning: true, vision: true, contextWindow: 2000000, maxTokens: 65536 },
  { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite (preview)", reasoning: false, vision: true, contextWindow: 1000000, maxTokens: 65536 },
  { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (preview)", reasoning: false, vision: true, contextWindow: 1000000, maxTokens: 65536 },
  { id: "gemini-3-pro-preview", name: "Gemini 3 Pro (preview)", reasoning: true, vision: true, contextWindow: 2000000, maxTokens: 65536 },
  { id: "grok-4-1-fast-reasoning", name: "Grok 4.1 Fast (reasoning)", reasoning: true, vision: true, contextWindow: 256000, maxTokens: 16384 },
  { id: "grok-4-1-fast-non-reasoning", name: "Grok 4.1 Fast (non-reasoning)", reasoning: false, vision: true, contextWindow: 256000, maxTokens: 16384 },
  { id: "grok-4-1-fast", name: "Grok 4.1 Fast", reasoning: false, vision: true, contextWindow: 256000, maxTokens: 16384 },
  { id: "grok-4", name: "Grok 4", reasoning: true, vision: true, contextWindow: 256000, maxTokens: 16384 },
  { id: "grok-3-mini-fast", name: "Grok 3 mini Fast", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "grok-3-mini", name: "Grok 3 mini", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "grok-3-fast", name: "Grok 3 Fast", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "grok-3", name: "Grok 3", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", reasoning: true, vision: false, contextWindow: 128000, maxTokens: 8192 },
  { id: "deepseek-v3.2-exp", name: "DeepSeek V3.2 (exp)", reasoning: false, vision: false, contextWindow: 128000, maxTokens: 8192 },
  { id: "deepseek-v3", name: "DeepSeek V3", reasoning: false, vision: false, contextWindow: 128000, maxTokens: 8192 },
  { id: "deepseek-reasoner", name: "DeepSeek Reasoner", reasoning: true, vision: false, contextWindow: 128000, maxTokens: 8192 },
  { id: "deepseek-r1", name: "DeepSeek R1", reasoning: true, vision: false, contextWindow: 128000, maxTokens: 8192 },
  { id: "kimi-k2.5", name: "Kimi K2.5", reasoning: true, vision: true, contextWindow: 262144, maxTokens: 16384 },
  { id: "kimi-k2-turbo-preview", name: "Kimi K2 Turbo (preview)", reasoning: false, vision: false, contextWindow: 200000, maxTokens: 8192 },
  { id: "kimi-k2-thinking-turbo", name: "Kimi K2 Thinking Turbo", reasoning: true, vision: false, contextWindow: 200000, maxTokens: 16384 },
  { id: "kimi-k2-thinking", name: "Kimi K2 Thinking", reasoning: true, vision: false, contextWindow: 200000, maxTokens: 16384 },
  { id: "kimi-k2-instruct-0905", name: "Kimi K2 Instruct (0905)", reasoning: false, vision: false, contextWindow: 200000, maxTokens: 8192 },
  { id: "glm-5.1", name: "GLM 5.1", reasoning: true, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-5-turbo", name: "GLM 5 Turbo", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-5", name: "GLM 5", reasoning: true, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-4.7", name: "GLM 4.7", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-4.6", name: "GLM 4.6", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-4.5v", name: "GLM 4.5V", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-4.5", name: "GLM 4.5", reasoning: false, vision: true, contextWindow: 128000, maxTokens: 8192 },
] as const;
