#!/usr/bin/env node
/** Project the reviewed public catalog into runtime and manifest entries. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = JSON.parse(
  readFileSync(join(root, "src/chat/model-catalog.json"), "utf8"),
);
const manifestPath = join(root, "openclaw.plugin.json");
const outputPath = join(root, "src/chat/generated-catalog.ts");
const ids = new Set();
const protocols = new Set([
  "openai-completions",
  "openai-responses",
  "anthropic-messages",
]);
const origins = new Set(["https://api.acedata.cloud"]);
const models = source.models.map(({ source: evidence, ...model }) => {
  if (
    ids.has(model.id) ||
    !model.id ||
    !protocols.has(model.api) ||
    !origins.has(new URL(model.baseUrl).origin)
  ) {
    throw new Error(`Invalid model identity or route: ${model.id}`);
  }
  ids.add(model.id);
  if (
    !evidence?.api ||
    !evidence?.package ||
    model.contextWindow <= 0 ||
    model.maxTokens <= 0
  ) {
    throw new Error(`Missing model evidence or limits: ${model.id}`);
  }
  for (const key of ["input", "output", "cacheRead", "cacheWrite"]) {
    if (!Number.isFinite(model.cost[key]) || model.cost[key] < 0)
      throw new Error(`Invalid ${key} price: ${model.id}`);
  }
  if (model.input.some((value) => !["text", "image"].includes(value)))
    throw new Error(`Unsupported input: ${model.id}`);
  return model;
});
if (!models.length) throw new Error("The public chat catalog is empty");
const rendered = `// AUTO-GENERATED by scripts/sync-catalog.mjs. DO NOT EDIT.
// Source: ${source.catalogUrl}; checked ${source.updatedAt}.
import type { OpenClawConfig } from "openclaw/plugin-sdk/config-contracts";
type Provider = NonNullable<NonNullable<OpenClawConfig["models"]>["providers"]>[string];
export type GeneratedCatalogEntry = Omit<Provider["models"][number], "api" | "input"> & {
  api: "openai-completions" | "openai-responses" | "anthropic-messages";
  baseUrl: string;
  input: Array<"text" | "image">;
  reasoningEfforts: string[];
  thinkingToggle: boolean;
};
export const GENERATED_CHAT_MODELS: readonly GeneratedCatalogEntry[] = ${JSON.stringify(models, null, 2)};
`;
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
manifest.modelCatalog = {
  providers: {
    acedatacloud: {
      baseUrl: "https://api.acedata.cloud/openai",
      api: "openai-completions",
      models: models.map(
        ({ reasoningEfforts, thinkingToggle, ...model }) => model,
      ),
    },
  },
};
const renderedManifest = `${JSON.stringify(manifest, null, 2)}\n`;
if (process.argv.includes("--check")) {
  if (
    readFileSync(outputPath, "utf8") !== rendered ||
    readFileSync(manifestPath, "utf8") !== renderedManifest
  ) {
    throw new Error("Catalog projections are stale; run pnpm sync-catalog");
  }
} else {
  writeFileSync(outputPath, rendered);
  writeFileSync(manifestPath, renderedManifest);
}
console.log(
  `Catalog ${process.argv.includes("--check") ? "verified" : "generated"}: ${models.length} models.`,
);
