#!/usr/bin/env node
/**
 * Sync src/chat/generated-catalog.ts from PlatformBackend/cost/api/_chat_models.json
 * (the canonical billing rule file). Capability metadata (reasoning, vision,
 * contextWindow, maxTokens, displayName, hidden) is merged from
 * src/chat/model-overrides.json.
 *
 * Usage:
 *   node scripts/sync-catalog.mjs [--source=<path>] [--check]
 *
 * Default --source resolves to:
 *   ../PlatformBackend/cost/api/_chat_models.json  (sibling layout)
 *
 * --check exits with code 1 if the generated file would differ from the
 * version on disk (intended for CI).
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import { argv, exit } from "node:process";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT_PATH = join(ROOT, "src/chat/generated-catalog.ts");
const OVERRIDES_PATH = join(ROOT, "src/chat/model-overrides.json");

function parseArgs(args) {
  const out = { check: false, source: resolve(ROOT, "../PlatformBackend/cost/api/_chat_models.json") };
  for (const a of args) {
    if (a === "--check") out.check = true;
    else if (a.startsWith("--source=")) out.source = resolve(a.slice("--source=".length));
  }
  return out;
}

function extractModels(conditions, acc) {
  if (!conditions || typeof conditions !== "object") return;
  for (const [op, args] of Object.entries(conditions)) {
    if (op === "==" && Array.isArray(args) && args.length === 2) {
      const [a, b] = args;
      const aIsModelVar = a && typeof a === "object" && Array.isArray(a.var) && a.var[0] === "model";
      const bIsModelVar = b && typeof b === "object" && Array.isArray(b.var) && b.var[0] === "model";
      if (aIsModelVar && typeof b === "string") acc.add(b);
      else if (bIsModelVar && typeof a === "string") acc.add(a);
    } else if (op === "in" && Array.isArray(args) && args.length === 2) {
      const [varPart, listPart] = args;
      const varIsModel = varPart && typeof varPart === "object" && Array.isArray(varPart.var) && varPart.var[0] === "model";
      if (varIsModel && Array.isArray(listPart)) {
        for (const x of listPart) if (typeof x === "string") acc.add(x);
      }
    } else if (op === "and" || op === "or") {
      if (Array.isArray(args)) for (const sub of args) extractModels(sub, acc);
    }
  }
}

function classify(id) {
  // family — for grouping display name when there's no override
  const lower = id.toLowerCase();
  if (lower.startsWith("claude-")) return "Claude";
  if (lower.startsWith("gpt-")) return "GPT";
  if (lower.match(/^o[1-9](-|$)/)) return "OpenAI";
  if (lower.startsWith("gemini-")) return "Gemini";
  if (lower.startsWith("grok-")) return "Grok";
  if (lower.startsWith("deepseek-")) return "DeepSeek";
  if (lower.startsWith("kimi-")) return "Kimi";
  if (lower.startsWith("glm-")) return "GLM";
  return "Model";
}

function defaultName(id, family) {
  return `${family} ${id.replace(/^(claude|gpt|gemini|grok|deepseek|kimi|glm)-/, "")}`.trim();
}

function buildEntries(modelIds, overrides) {
  const entries = [];
  for (const id of modelIds) {
    const o = overrides[id] ?? {};
    if (o.hidden) continue;
    const family = classify(id);
    entries.push({
      id,
      name: o.displayName ?? defaultName(id, family),
      reasoning: Boolean(o.reasoning ?? false),
      vision: Boolean(o.vision ?? false),
      contextWindow: o.contextWindow ?? 128000,
      maxTokens: o.maxTokens ?? 8192,
      family,
    });
  }
  // sort: by family group (priority order), then by id desc so newest appears first
  const familyOrder = ["Claude", "GPT", "OpenAI", "Gemini", "Grok", "DeepSeek", "Kimi", "GLM", "Model"];
  entries.sort((a, b) => {
    const fa = familyOrder.indexOf(a.family);
    const fb = familyOrder.indexOf(b.family);
    if (fa !== fb) return fa - fb;
    return a.id < b.id ? 1 : a.id > b.id ? -1 : 0;
  });
  return entries;
}

function render(entries, sourceFile) {
  const lines = [];
  lines.push("// AUTO-GENERATED by scripts/sync-catalog.mjs. DO NOT EDIT.");
  lines.push("// Run: pnpm sync-catalog");
  lines.push(`// Source: ${sourceFile.replace(/^.*\/PlatformBackend\//, "PlatformBackend/")}`);
  lines.push("");
  lines.push("export type GeneratedCatalogEntry = {");
  lines.push("  id: string;");
  lines.push("  name: string;");
  lines.push("  reasoning: boolean;");
  lines.push("  vision: boolean;");
  lines.push("  contextWindow: number;");
  lines.push("  maxTokens: number;");
  lines.push("};");
  lines.push("");
  lines.push("export const GENERATED_CHAT_MODELS: readonly GeneratedCatalogEntry[] = [");
  for (const e of entries) {
    lines.push(`  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, reasoning: ${e.reasoning}, vision: ${e.vision}, contextWindow: ${e.contextWindow}, maxTokens: ${e.maxTokens} },`);
  }
  lines.push("] as const;");
  lines.push("");
  return lines.join("\n");
}

const args = parseArgs(argv.slice(2));

if (!existsSync(args.source)) {
  console.error(`source file not found: ${args.source}`);
  console.error("Provide --source=/path/to/_chat_models.json");
  exit(2);
}

const rules = JSON.parse(readFileSync(args.source, "utf-8"));
if (!Array.isArray(rules)) {
  console.error("source file is not a JSON array");
  exit(2);
}

const ids = new Set();
for (const rule of rules) extractModels(rule.conditions, ids);
if (ids.size === 0) {
  console.error("no model ids extracted from source");
  exit(2);
}

const overrides = JSON.parse(readFileSync(OVERRIDES_PATH, "utf-8"));
delete overrides._comment;

// Report missing overrides so they can be added intentionally.
const missing = [...ids].filter((id) => !(id in overrides));
if (missing.length > 0) {
  console.warn(`warning: no override entry for ${missing.length} models (will use defaults):`);
  for (const m of missing.sort()) console.warn(`  ${m}`);
}

const entries = buildEntries([...ids].sort(), overrides);
const rendered = render(entries, args.source);

if (args.check) {
  const current = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, "utf-8") : "";
  if (current === rendered) {
    console.log(`OK — generated catalog matches (${entries.length} models from ${ids.size} source ids).`);
    exit(0);
  }
  console.error("FAIL — generated catalog is out of date. Run: pnpm sync-catalog");
  exit(1);
}

writeFileSync(OUT_PATH, rendered, "utf-8");
console.log(`Wrote ${OUT_PATH} (${entries.length} visible models from ${ids.size} source ids).`);
